### PR TITLE
Fix voting by passing variables

### LINKED ISSUE #2: Voting doesn't work
I get the error

errorHandling.js?e4be:7 Error: Can't find field allLinks({}) on object (ROOT_QUERY) {
  "allLinks({\"first\":5,\"skip\":5,\"orderBy\":\"createdAt_DESC\"})": [

It worked fine before the pagination step, but I haven't figured yet what's the problem.

Thanks!

### PR DESCRIPTION
**Pull request by pelletiermaxime**
Fixes #2.

### CODE REVIEW

**Review by Akryum — CHANGES_REQUESTED** [review]
You should write the query with the same variables you red it. See an example [here](https://github.com/Akryum/vue-apollo-todos/blob/master/src/components/TodoCreate.vue#L72).

**Comment by pelletiermaxime** [comment]
Done. Sorry, I had not read about all the read/write query stuff and it completly changes the usual way to write Vue.

**Comment by Matt-Dionis** [comment]
@Akryum I know this is an old PR at this point, but could you approve (or not 😄) when you get a chance. I'm going to be updating this repo shortly and want to land this fix first. Thanks!

**Comment by Matt-Dionis** [comment]
Tested this locally and it looks good! Sorry this took so long to review and merge.

**Pull request merged**
